name: Build Branch

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Get Gox
        run: go get github.com/mitchellh/gox

      - name: Build for Linux
        run: gox -output="build/{{.Dir}}_{{.OS}}_{{.Arch}}" -os="linux" -arch="amd64" -cgo

      - name: Build for Windows
        run: gox -output="build/{{.Dir}}_{{.OS}}_{{.Arch}}" -os="windows" -arch="amd64" -cgo

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}